In [1]:
import numpy as np
from forward_pass import forward_pass
from NeuralNet import Linear

In [2]:
X = np.array([
	[100, 3, 2],
	[150, 5, 3],
	[175, 5, 4],
	[200, 6, 3],
])

Y = np.array([
	[500], 
	[850], 
	[900], 
	[1100]
])

# ============ PARAMETERS - LAYER 1 ============
W = np.array([
	[0.1, 0.4],
	[0.2, 0.5],
	[0.3, 0.6],
])

B = np.array([0.0, 0.0])

In [3]:
output = forward_pass(X, W, B)
print(output)

[[11.2 42.7]
 [16.9 64.3]
 [19.7 74.9]
 [22.1 84.8]]


In [4]:
# ============ PARAMETERS - LAYER 2 ============
W_2 = np.array([
	[0.15, 0.45, 0.65],
	[0.25, 0.55, 0.75],
])

B_2 = np.array([0.0, 0.0, 0.0])

# ============ FORWARD PASS ============
# X dim: (4, 3), W dim: (3, 2), B' dim: (4, 2) -> Z_1 dim: (4, 2)
Z_1 = np.dot(X, W) + B
# Z_1 dim: (4, 2), W dim: (2, 3), B' dim: (4, 3) -> Z_2 dim: (4, 3)
Z_2 = np.dot(Z_1, W_2) + B_2
print(Z_2)

[[12.355 28.525 39.305]
 [18.61  42.97  59.21 ]
 [21.68  50.06  68.98 ]
 [24.515 56.585 77.965]]


In [5]:
# ============ PARAMETERS - OUTPUT LAYER ============
W_output = np.array([
	[0.15],
	[0.25],
	[0.35],
])

B_output = np.array([0.0])

# ============ FORWARD PASS ============
# X dim: (4, 3), W dim: (3, 2), B' dim: (4, 2) -> Z_1 dim: (4, 2)
Z_1 = np.dot(X, W) + B
# Z_1 dim: (4, 2), W dim: (2, 3), B' dim: (4, 3) -> Z_2 dim: (4, 3)
Z_2 = np.dot(Z_1, W_2) + B_2
# Z_2 dim: (4, 3), W dim: (3, 1), B' dim: (4, 1) -> Z_2 dim: (4, 1)
Y_pred = np.dot(Z_2, W_output) + B_output
print(Y_pred)

[[22.74125]
 [34.2575 ]
 [39.91   ]
 [45.11125]]


In [6]:
np.random.seed(1)

X = np.array([
	[100, 3, 2],
	[150, 5, 3],
	[175, 5, 4],
	[200, 6, 3],
])

# ============ PARAMETERS - LAYER 1 ============
W = np.random.randn(3, 2) * 0.01
B = np.zeros((1, 2))

# ============ PARAMETERS - LAYER 2 ============
W_2 =  np.random.randn(2, 3) * 0.01
B_2 = np.zeros((1, 3))

# ============ PARAMETERS - OUTPUT LAYER ============
W_output = np.random.randn(3, 1) * 0.01
B_output = np.zeros((1, 1)) 

# ============ FORWARD PASS ============
# X dim: (4, 3), W dim: (3, 2), B' dim: (4, 2) -> Z_1 dim: (4, 2)
Z_1 = np.dot(X, W) + B
# Z_1 dim: (4, 2), W dim: (2, 3), B' dim: (4, 3) -> Z_2 dim: (4, 3)
Z_2 = np.dot(Z_1, W_2) + B_2
# Z_2 dim: (4, 3), W dim: (3, 1), B' dim: (4, 1) -> Z_2 dim: (4, 1)
Y_pred = np.dot(Z_2, W_output) + B_output
print(Y_pred)

[[0.00020923]
 [0.00031534]
 [0.0003687 ]
 [0.0004119 ]]


In [ ]:
# Set seed untuk reproducibility
np.random.seed(1)

X = np.array([
	[100, 3, 2],
	[150, 5, 3],
	[175, 5, 4],
	[200, 6, 3],
])

# Inisialisasi layer-layer
# Layer 1: 3 input -> 2 output
input_to_hidden_layer = Linear(in_features=3, out_features=2) 
# Layer 2: 2 input -> 3 output
hidden_to_hidden_layer = Linear(in_features=2, out_features=3)
  # Layer 3: 3 input -> 1 output
hidden_to_output_layer = Linear(in_features=3, out_features=1)

# Forward pass melalui jaringan
Z_1 = input_to_hidden_layer.forward(X)  # Output dari layer 1
Z_2 = hidden_to_hidden_layer.forward(Z_1)  # Output dari layer 2
Y_pred = hidden_to_output_layer.forward(Z_2)  # Output akhir

# Cetak hasil prediksi
print("Final output shape:", Y_pred.shape)
print("Final output:\n", Y_pred)

Final output shape: (4, 1)
Final output:
 [[0.00020923]
 [0.00031534]
 [0.0003687 ]
 [0.0004119 ]]
