In [ ]:
import numpy as np
from NeuralNet import Linear
from NeuralNet import MeanSquaredError

In [2]:
# Set seed untuk reproducibility
np.random.seed(1)

X = np.array([
	[100, 3, 2],
	[150, 5, 3],
	[175, 5, 4],
	[200, 6, 3],
])

# Inisialisasi layer-layer
input_to_hidden_layer = Linear(in_features=3, out_features=2)  # Layer 1: 3 input -> 2 output
hidden_to_hidden_layer = Linear(in_features=2, out_features=3)  # Layer 2: 2 input -> 3 output
hidden_to_output_layer = Linear(in_features=3, out_features=1)  # Layer 3: 3 input -> 1 output

# Forward pass melalui jaringan
Z_1 = input_to_hidden_layer.forward(X)  # Output dari layer 1
Z_2 = hidden_to_hidden_layer.forward(Z_1)  # Output dari layer 2
Y_pred = hidden_to_output_layer.forward(Z_2)  # Output akhir

# Cetak hasil prediksi
print("Final output shape:", Y_pred.shape)
print("Final output:\n", Y_pred)

Final output shape: (4, 1)
Final output:
 [[0.00020923]
 [0.00031534]
 [0.0003687 ]
 [0.0004119 ]]


In [3]:
Y = np.array([
	[500],
	[850],
	[900],
	[1100],
])

Y_pred = np.array([
 [0.00020923],
 [0.00031534],
 [0.0003687 ],
 [0.0004119 ]
])

# Hitung selisih antara prediksi dan target
element_wise_error = Y - Y_pred
print("nilai sebenarnya (target):\n", Y)
print("\nnilai prediksi:\n", Y_pred)
print("\nelement wise error:\n", element_wise_error)

nilai sebenarnya (target):
 [[ 500]
 [ 850]
 [ 900]
 [1100]]

nilai prediksi:
 [[0.00020923]
 [0.00031534]
 [0.0003687 ]
 [0.0004119 ]]

element wise error:
 [[ 499.99979077]
 [ 849.99968466]
 [ 899.9996313 ]
 [1099.9995881 ]]


In [4]:
Y = np.array([
	[500],
	[850],
	[900],
	[1100],
])

Y_pred = np.array([
 [0.00020923],
 [0.00031534],
 [0.0003687 ],
 [0.0004119 ]
])

# Hitung selisih antara prediksi dan target
element_wise_error = Y - Y_pred
print("element wise error:\n", element_wise_error)

# Kuadratkan selisih
squared_error = np.square(element_wise_error)
print("\nsquared error:\n", squared_error)

element wise error:
 [[ 499.99979077]
 [ 849.99968466]
 [ 899.9996313 ]
 [1099.9995881 ]]

squared error:
 [[ 249999.79077004]
 [ 722499.4639221 ]
 [ 809999.33634014]
 [1209999.09382017]]


In [5]:
Y = np.array([
	[500],
	[850],
	[900],
	[1100],
])

Y_pred = np.array([
 [0.00020923],
 [0.00031534],
 [0.0003687 ],
 [0.0004119 ]
])

# Hitung selisih antara prediksi dan target
element_wise_error = Y - Y_pred
print("element wise error:\n", element_wise_error)


# Kuadratkan selisih
squared_error = np.square(element_wise_error)
print("\nsquared error:\n", squared_error)

# Hitung rata-rata dari kuadrat selisih
mse_loss = np.mean(squared_error)
print("\nMSE Loss:", mse_loss)

element wise error:
 [[ 499.99979077]
 [ 849.99968466]
 [ 899.9996313 ]
 [1099.9995881 ]]

squared error:
 [[ 249999.79077004]
 [ 722499.4639221 ]
 [ 809999.33634014]
 [1209999.09382017]]

MSE Loss: 748124.4212131122


In [ ]:
Y = np.array([
	[500],
	[850],
	[900],
	[1100],
])

Y_pred = np.array([
 [0.00020923],
 [0.00031534],
 [0.0003687 ],
 [0.0004119 ]
])

# Hitung rata-rata dari kuadrat selisih
loss = MeanSquaredError()
mse_loss = loss.calculate(Y, Y_pred)
print("MSE Loss:", mse_loss)

MSE Loss: 748124.4212131122
